//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUGIMPL_OME.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SUGIMPL_OME.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IMG_ImportDocuments {
            get {
                object obj = ResourceManager.GetObject("IMG_ImportDocuments", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* SUGIMPL_OME Data Model */
        ///--&gt; Version 1
        ///--&gt; Nuno Queirós
        ///--&gt; 19.09.2020
        ///
        ///
        ////**********************************************
        ///			CDUs
        ///**********************************************/
        ///IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE Name = N&apos;CDU_ArtigoGrupo&apos; AND Object_ID = Object_ID(N&apos;dbo.Artigo&apos;)) ALTER TABLE Artigo ADD CDU_ArtigoGrupo BIT NOT NULL DEFAULT 0
        ///IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE Name = N&apos;CDU_Exportado&apos; AND Object_ID = Object_ID(N&apos;dbo.CabecCompras&apos;)) ALTER TABLE CabecCompras  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UPG_1 {
            get {
                return ResourceManager.GetString("UPG_1", resourceCulture);
            }
        }
    }
}
