//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Primavera.TemplateProcurement.Extensibility.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sql() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Primavera.TemplateProcurement.Extensibility.Resource.Sql", typeof(Sql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Case CDU_Atribuido 
        ///		when &apos;1&apos; then CDU_Autor
        ///		when &apos;2&apos; then OUS.Manager
        ///		when &apos;3&apos; then case when isnull(OUS.PurchasingManager ,&apos;&apos;) = &apos;&apos; then CMP.PurchasingManager else OUS.PurchasingManager end
        ///		else AP.Approver
        ///		end Approver
        ///FROM CabecCompras CC
        ///INNER JOIN @3@.dbo.PortalComprasOrganizationalUnits OUS ON OUS.OrganizationalUnit = CC.CDU_OrganizationalUnit
        ///INNER JOIN @3@.dbo.PortalComprasCompanies CMP ON CMP.Primavera = RIGHT(DB_NAME(),len(DB_NAME())-3)
        ///LEFT JOIN  @3@.dbo.PortalComprasApp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetFromPRIOMNIA_Approver {
            get {
                return ResourceManager.GetString("GetFromPRIOMNIA_Approver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT CDU_Empresa, CDU_Endpoint, CDU_Tenant, CDU_ClientId, CDU_ClientSecret, CDU_OmniaDB FROM TDU_TemplateProcurement_Config WHERE CDU_Empresa = @1@.
        /// </summary>
        internal static string GetFromTDU_Config {
            get {
                return ResourceManager.GetString("GetFromTDU_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT CDU_OrganizationalUnit, CDU_Autor, CDU_AutorNome FROM CabecInternos
        ///WHERE CDU_CodOmnia = @1@.
        /// </summary>
        internal static string GetInternos_CDU {
            get {
                return ResourceManager.GetString("GetInternos_CDU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT CDU_CodOmnia FROM CabecInternos CI
        ///INNER JOIN LinhasInternos LI ON LI.IdCabecInternos = CI.Id
        ///WHERE LI.Id = @1@.
        /// </summary>
        internal static string GetInternos_CodOmniaByLineId {
            get {
                return ResourceManager.GetString("GetInternos_CodOmniaByLineId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 1 FROM INV_DocumentosTransferencia
        ///WHERE Documento = @1@ AND TipoTransferencia = 0
        ///AND TransfereArmazem = 1 AND TransfereLocalizacao = 1.
        /// </summary>
        internal static string GetInv_DocTrans {
            get {
                return ResourceManager.GetString("GetInv_DocTrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO TDU_FinancialDocumentPaymentApprovalFlow(DocID, ApprovalProfile, Ordem, Amount) VALUES (@1@,@2@,@3@,@4@).
        /// </summary>
        internal static string InsertIntoFinancialDocumentPaymentApprovalFlow {
            get {
                return ResourceManager.GetString("InsertIntoFinancialDocumentPaymentApprovalFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to declare @ordem int 
        ///    if not exists(Select Campo from [StdCamposVar] where Tabela = &apos;CabecInternos&apos; and  Campo = &apos;CDU_CodOmnia&apos;)
        ///    begin
        ///        alter table CabecInternos
        ///        add  CDU_CodOmnia varchar(30)
        ///        Select @ordem = max(Ordem) +1 from [StdCamposVar] where Tabela = &apos;CabecInternos&apos;
        ///        INSERT INTO [StdCamposVar] (Tabela,Campo,Descricao,Query,Texto,Visivel, Ordem,ValorDefeito) VALUES (&apos;CabecInternos&apos;,&apos;CDU_CodOmnia&apos;,&apos;OMNIA ID&apos;,&apos;&apos;,&apos;OMNIA ID&apos;,1,@ordem,null)  
        ///    end                [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StdUp {
            get {
                return ResourceManager.GetString("StdUp", resourceCulture);
            }
        }
    }
}
