//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cegid.Export2XML.XML2XRP.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cegid.Export2XML.XML2XRP.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artículo.
        /// </summary>
        internal static string RES_Artigo {
            get {
                return ResourceManager.GetString("RES_Artigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio Punto Verde &apos;{0}&apos; (campo no mapeado en XRP).
        /// </summary>
        internal static string RES_ArtigoWarn1 {
            get {
                return ResourceManager.GetString("RES_ArtigoWarn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artículo con Descripción vacía..
        /// </summary>
        internal static string RES_ArtigoWarn3 {
            get {
                return ResourceManager.GetString("RES_ArtigoWarn3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código del artículo sustitutivo no puede ser el mismo que el código del artículo..
        /// </summary>
        internal static string RES_ArtigoWarn4 {
            get {
                return ResourceManager.GetString("RES_ArtigoWarn4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente Intragrupo (campo no asignado en XRP).
        /// </summary>
        internal static string RES_ClienteWarn1 {
            get {
                return ResourceManager.GetString("RES_ClienteWarn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El cliente no tiene número de identificación fiscal..
        /// </summary>
        internal static string RES_ClienteWarn3 {
            get {
                return ResourceManager.GetString("RES_ClienteWarn3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandato SEPA por valor de 0 EUR.
        /// </summary>
        internal static string RES_ClienteWarn4 {
            get {
                return ResourceManager.GetString("RES_ClienteWarn4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente con nombre vacío..
        /// </summary>
        internal static string RES_ClienteWarn7 {
            get {
                return ResourceManager.GetString("RES_ClienteWarn7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forma de Pago.
        /// </summary>
        internal static string RES_CondPagam {
            get {
                return ResourceManager.GetString("RES_CondPagam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La forma de pago se ha creado con diferencias..
        /// </summary>
        internal static string RES_ConPagWarn1 {
            get {
                return ResourceManager.GetString("RES_ConPagWarn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        internal static string RES_EntityCliente {
            get {
                return ResourceManager.GetString("RES_EntityCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proveedor.
        /// </summary>
        internal static string RES_EntityFornecedor {
            get {
                return ResourceManager.GetString("RES_EntityFornecedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otro deudor/acreedor.
        /// </summary>
        internal static string RES_EntityThirdParty {
            get {
                return ResourceManager.GetString("RES_EntityThirdParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proveedor con nombre vacío..
        /// </summary>
        internal static string RES_FornecedorWarn2 {
            get {
                return ResourceManager.GetString("RES_FornecedorWarn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Proveedor no tiene número de identificación fiscal..
        /// </summary>
        internal static string RES_FornWarn1 {
            get {
                return ResourceManager.GetString("RES_FornWarn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El NIF no empieza por &apos;{0}&apos;..
        /// </summary>
        internal static string RES_GenWarn2 {
            get {
                return ResourceManager.GetString("RES_GenWarn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El archivo &apos;DatosEmpresaGES.xml&apos; no existe en la parte de datos..
        /// </summary>
        internal static string RES_NoCompanyFile {
            get {
                return ResourceManager.GetString("RES_NoCompanyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No indicado..
        /// </summary>
        internal static string RES_PortesNaoIndicado {
            get {
                return ResourceManager.GetString("RES_PortesNaoIndicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagado..
        /// </summary>
        internal static string RES_PortesPago {
            get {
                return ResourceManager.GetString("RES_PortesPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pendiente..
        /// </summary>
        internal static string RES_PortesPendente {
            get {
                return ResourceManager.GetString("RES_PortesPendente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El otro deudor/acreedor no tiene número de identificación fiscal..
        /// </summary>
        internal static string RES_ThirdPartyWarn1 {
            get {
                return ResourceManager.GetString("RES_ThirdPartyWarn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otro deudor/acreedor intragrupo (campo no asignado en XRP).
        /// </summary>
        internal static string RES_ThirdPartyWarn11 {
            get {
                return ResourceManager.GetString("RES_ThirdPartyWarn11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otro deudor/acreedor con un nombre vacío..
        /// </summary>
        internal static string RES_ThirdPartyWarn3 {
            get {
                return ResourceManager.GetString("RES_ThirdPartyWarn3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendedor con nombre vacío..
        /// </summary>
        internal static string RES_VendedorWarn1 {
            get {
                return ResourceManager.GetString("RES_VendedorWarn1", resourceCulture);
            }
        }
    }
}
