INSERT INTO Bot.BotTopics(NaturalKey, DescriptionId, CreatedBy, ModifiedBy)
VALUES('DevelopersNetworkTopic', 'Topic_DevelopersNetwork', 'MyUser', 'MyUser')

DECLARE @TopicId INT

-- Gets the topic unique identifier (auto generated by SQL) based on its natural key
SET @TopicId = (SELECT TOP 1 Id FROM Bot.BotTopics WHERE NaturalKey = 'DevelopersNetworkTopic')

INSERT INTO Bot.BotTasks(NaturalKey, DescriptionId, TopicId, Importance, ScheduleConfig, MessageConfig, PlatformsConfig, PipelineConfig, [System], Active, CreatedBy, ModifiedBy, AllowConfigReceivers, ReceiverOption, [Version])
VALUES('TaskExecutionExample', 'Task_ExecutionExample', @TopicId, 1,
'{"Active":true,"Execute":""Daily"","StartAt":1,"StartTolerance":31}',
'{"Scope":"Instance","ExpireDays":365}',
'[{"Version":"V100", "platform":"Executive"},{"Version":"V100", "platform":"Professional"}]',
'<Pipeline Id="TaskExecutionExamplePipeline">
	<Handlers>
		<Handler Id="ErpReadConfigHandler" Order="1" Behavior="Reader" Type="Primavera.Platform.HurakanHandlers.ErpReadConfig" ConfigStr="instanceIdFilter=%%InstanceId%%;userFiltler=%%UserFilter%%;enterpriseFilter=%%EnterpriseFilter%%"/>
		<Handler Id="TaskExecutionExampleHandler" Order="2" Behavior="Reader" Type="Primavera.Bot.DevelopersNetworkTopic.Handlers.TaskExecutionExampleHandler" ConfigStr="topicId=%%TopicId%%;taskId=%%TaskId%%"/>
		<Handler Id="CreateUserBotMessagesHandler" Order="3" Behavior="Reader" Type="Primavera.Hurakan.BotHandlers.CreateUserBotMessages" ConfigStr=""/>
		<Handler Id="SaveBotMessagesHandler" Order="4" Behavior="Reader" Type="Primavera.Hurakan.BotHandlers.SaveBotMessages" ConfigStr=""/>
	</Handlers>
</Pipeline>',
0, 1, 'MyUser', 'MyUser', 1, -1, 1)

-- Portuguese
INSERT INTO Bot.BotStringTable(ResourceId, [Language], [Text], CreatedBy, ModifiedBy)
VALUES('Topic_DevelopersNetwork', 'pt', 'Tópico de Template Developers Network', 'MyUser', 'MyUser')
INSERT INTO Bot.BotStringTable(ResourceId, [Language], [Text], CreatedBy, ModifiedBy)
VALUES('Task_ExecutionExample', 'pt', 'Exemplo de execução', 'MyUser', 'MyUser')
-- English
INSERT INTO Bot.BotStringTable(ResourceId, [Language], [Text], CreatedBy, ModifiedBy)
VALUES('Topic_DevelopersNetwork', 'en', 'Developers Network Template Topic', 'MyUser', 'MyUser')
INSERT INTO Bot.BotStringTable(ResourceId, [Language], [Text], CreatedBy, ModifiedBy)
VALUES('Task_ExecutionExample', 'en', ' Execution example', 'MyUser', 'MyUser')