//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Primavera.TemplateProcurement.Extensibility.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Primavera.TemplateProcurement.Extensibility.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existem campos inválidos.
        /// </summary>
        public static string RES_CamposInvalidos {
            get {
                return ResourceManager.GetString("RES_CamposInvalidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente Id está vazio.
        /// </summary>
        public static string RES_ClientIdVazio {
            get {
                return ResourceManager.GetString("RES_ClientIdVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente Secret está vazio.
        /// </summary>
        public static string RES_ClientSecretVazio {
            get {
                return ResourceManager.GetString("RES_ClientSecretVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint da API está vazio.
        /// </summary>
        public static string RES_EndpointApiVazio {
            get {
                return ResourceManager.GetString("RES_EndpointApiVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint do Identity está vazio.
        /// </summary>
        public static string RES_EndpointIdentityVazio {
            get {
                return ResourceManager.GetString("RES_EndpointIdentityVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O endpoint {0} não é válido..
        /// </summary>
        public static string RES_EndpointInvalido {
            get {
                return ResourceManager.GetString("RES_EndpointInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint está vazio.
        /// </summary>
        public static string RES_EndpointVazio {
            get {
                return ResourceManager.GetString("RES_EndpointVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro na gravação..
        /// </summary>
        public static string RES_ErroGravacao {
            get {
                return ResourceManager.GetString("RES_ErroGravacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao gravar configuração OMNIA.
        /// </summary>
        public static string RES_ErroGravarOmnia {
            get {
                return ResourceManager.GetString("RES_ErroGravarOmnia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao initializar OMNIA ApiClient {0}.
        /// </summary>
        public static string RES_ErroInicializacao {
            get {
                return ResourceManager.GetString("RES_ErroInicializacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ficheiro de extensibilidade não encontrado.
        /// </summary>
        public static string RES_ExtensibilidadeNaoEncontrado {
            get {
                return ResourceManager.GetString("RES_ExtensibilidadeNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerir Acessos V10 Mobile.
        /// </summary>
        public static string RES_FormName {
            get {
                return ResourceManager.GetString("RES_FormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V10 Mobile - Configuração e Gestão de Acessos.
        /// </summary>
        public static string RES_FormTitle {
            get {
                return ResourceManager.GetString("RES_FormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A aplicação V10 Mobile apenas está disponível para instalações licenciadas..
        /// </summary>
        public static string RES_LicensingInformationNotFound {
            get {
                return ResourceManager.GetString("RES_LicensingInformationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A configuração dos parâmetros OMNIA apenas está disponível para instalações licenciadas..
        /// </summary>
        public static string RES_LicensingInformationProcurementNotFound {
            get {
                return ResourceManager.GetString("RES_LicensingInformationProcurementNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não existe configuração OMNIA para a empresa: &apos;{0}&apos;.
        /// </summary>
        public static string RES_NaoExisteConfi {
            get {
                return ResourceManager.GetString("RES_NaoExisteConfi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OMNIA DB está vazio.
        /// </summary>
        public static string RES_OmniaDBVazio {
            get {
                return ResourceManager.GetString("RES_OmniaDBVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuração e Gestão de Acessos.
        /// </summary>
        public static string RES_Permissions {
            get {
                return ResourceManager.GetString("RES_Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parâmetros OMNIA.
        /// </summary>
        public static string RES_PermissionsOmnia {
            get {
                return ResourceManager.GetString("RES_PermissionsOmnia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A aplicação V10 Mobile está disponivel apenas para empresas produtivas..
        /// </summary>
        public static string RES_ProductiveCompaniesOnlyInformation {
            get {
                return ResourceManager.GetString("RES_ProductiveCompaniesOnlyInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravado com sucesso, deve abrir o ERP Novamente para iniciar o Serviço do OMNIA.
        /// </summary>
        public static string RES_Sucesso {
            get {
                return ResourceManager.GetString("RES_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant está vazio.
        /// </summary>
        public static string RES_TenantVazio {
            get {
                return ResourceManager.GetString("RES_TenantVazio", resourceCulture);
            }
        }
    }
}
