//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Primavera.Platform.Geolocation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Primavera.Platform.Geolocation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretende remover o marcador: [{0}] do mapa?.
        /// </summary>
        internal static string RES_DeleteMapMarker {
            get {
                return ResourceManager.GetString("RES_DeleteMapMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretende apagar a rota: [{0}] da sua lista?.
        /// </summary>
        internal static string RES_DeleteRoute {
            get {
                return ResourceManager.GetString("RES_DeleteRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretende apagar o marcador selecionado: [{0}] da sua lista?.
        /// </summary>
        internal static string RES_DeleteUserMarker {
            get {
                return ResourceManager.GetString("RES_DeleteUserMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este marcador é usado em pelo menos uma rota. Pretende apagar o marcador selecionado: [{0}] da sua lista?.
        /// </summary>
        internal static string RES_DeleteUserRouteMarker {
            get {
                return ResourceManager.GetString("RES_DeleteUserRouteMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para usar as funcionalidades da Geolocalização deverá escolher o tipo de mapa a partir da lista de opções..
        /// </summary>
        internal static string RES_GeolocationWarning {
            get {
                return ResourceManager.GetString("RES_GeolocationWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFORMAÇÃO.
        /// </summary>
        internal static string RES_GeolocationWarningTitle {
            get {
                return ResourceManager.GetString("RES_GeolocationWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretende guardar este marcador como ponto de interesse?.
        /// </summary>
        internal static string RES_MarkerPOI {
            get {
                return ResourceManager.GetString("RES_MarkerPOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possivel guardar a rota. É necessário guardar o marcador {0}..
        /// </summary>
        internal static string RES_RouteUnsavedMarker {
            get {
                return ResourceManager.GetString("RES_RouteUnsavedMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possivel guardar a rota, pois contêm marcadores por guardar. Deseja guardá-los?.
        /// </summary>
        internal static string RES_RouteUnsavedMarkers {
            get {
                return ResourceManager.GetString("RES_RouteUnsavedMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha o nome pretendido para o marcador..
        /// </summary>
        internal static string RES_SaveMarker {
            get {
                return ResourceManager.GetString("RES_SaveMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar Marcador.
        /// </summary>
        internal static string RES_SaveMarkerTitle {
            get {
                return ResourceManager.GetString("RES_SaveMarkerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha o nome pretendido para a rota..
        /// </summary>
        internal static string RES_SaveRoute {
            get {
                return ResourceManager.GetString("RES_SaveRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para guardar uma rota tem de calcular uma rota..
        /// </summary>
        internal static string RES_SaveRouteCalculateWarning {
            get {
                return ResourceManager.GetString("RES_SaveRouteCalculateWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para guardar uma rota tem de ter marcadores..
        /// </summary>
        internal static string RES_SaveRouteMarkersWarning {
            get {
                return ResourceManager.GetString("RES_SaveRouteMarkersWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possivel guardar a rota. É necessário dar-lhe um nome..
        /// </summary>
        internal static string RES_SaveRouteNameWarning {
            get {
                return ResourceManager.GetString("RES_SaveRouteNameWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar Rota.
        /// </summary>
        internal static string RES_SaveRouteTitle {
            get {
                return ResourceManager.GetString("RES_SaveRouteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor introduza a chave do Servidor de {0}.
        /// </summary>
        internal static string RES_ServerKeyName {
            get {
                return ResourceManager.GetString("RES_ServerKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurar Servidor de Mapa.
        /// </summary>
        internal static string RES_ServerKeyTitle {
            get {
                return ResourceManager.GetString("RES_ServerKeyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para traçar uma rota têm de ter pelo menos 2 marcadores..
        /// </summary>
        internal static string RES_TwoMarkerWarning {
            get {
                return ResourceManager.GetString("RES_TwoMarkerWarning", resourceCulture);
            }
        }
    }
}
